language: node_js
node_js:
  - "4"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
  sauce_connect:
    username: "circlingthesun"
    access_key: "6a02cad8-6284-41b2-bb28-72b4efc2ce8b"
before_script:
  - npm install -g gulp jspm
  - npm install
  - jspm install
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script: gulp test
